[2021-04-26 20:20:23,503] INFO Unable to read additional data from server sessionid 0x1000009d4720002, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:23,549] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1378145835, epoch=5429) to node 0: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 0 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-04-26 20:20:23,514] INFO [GroupCoordinator 1]: Member consumer-console-consumer-45195-1-456bde98-b83e-4460-bcd1-5ffe32040c56 in group console-consumer-45195 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-04-26 20:20:23,514] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9091-127.0.0.1:64483-1 (kafka.network.Processor)
[2021-04-26 20:20:35,060] INFO [GroupCoordinator 1]: Preparing to rebalance group console-consumer-45195 in state PreparingRebalance with old generation 1 (__consumer_offsets-25) (reason: removing member consumer-console-consumer-45195-1-456bde98-b83e-4460-bcd1-5ffe32040c56 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-04-26 20:20:35,082] INFO [GroupCoordinator 1]: Group console-consumer-45195 with generation 2 is now empty (__consumer_offsets-25) (kafka.coordinator.group.GroupCoordinator)
[2021-04-26 20:20:35,051] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1378145835, epoch=5429), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 0 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:110)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:217)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:317)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:141)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:140)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:140)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:123)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2021-04-26 20:20:35,175] INFO [GroupCoordinator 1]: Preparing to rebalance group console-consumer-45195 in state PreparingRebalance with old generation 2 (__consumer_offsets-25) (reason: Adding new member consumer-console-consumer-45195-1-a2cddd8a-4ad3-4d84-895b-4632252c971e with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-04-26 20:20:35,202] INFO [GroupCoordinator 1]: Stabilized group console-consumer-45195 generation 3 (__consumer_offsets-25) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2021-04-26 20:20:35,316] INFO [GroupCoordinator 1]: Assignment received from leader for group console-consumer-45195 for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2021-04-26 20:20:36,534] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:36,538] INFO Socket connection established, initiating session, client: /127.0.0.1:65028, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:36,542] WARN Unable to reconnect to ZooKeeper service, session 0x1000009d4720002 has expired (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:36,544] INFO Unable to reconnect to ZooKeeper service, session 0x1000009d4720002 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:36,548] INFO EventThread shut down for session: 0x1000009d4720002 (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:36,549] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2021-04-26 20:20:36,557] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2021-04-26 20:20:36,557] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@72ef8d15 (org.apache.zookeeper.ZooKeeper)
[2021-04-26 20:20:36,563] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2021-04-26 20:20:36,568] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:36,572] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:36,575] INFO Socket connection established, initiating session, client: /127.0.0.1:65029, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:36,650] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x1000009d4720008, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:20:36,668] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2021-04-26 20:20:37,409] INFO Creating /brokers/ids/1 (is it secure? false) (kafka.zk.KafkaZkClient)
[2021-04-26 20:20:37,478] INFO Stat of the created znode at /brokers/ids/1 is: 195,195,1619461237431,1619461237431,1,0,0,72057636256874504,202,0,195
 (kafka.zk.KafkaZkClient)
[2021-04-26 20:20:37,479] INFO Registered broker 1 at path /brokers/ids/1 with addresses: PLAINTEXT://localhost:9091, czxid (broker epoch): 195 (kafka.zk.KafkaZkClient)
[2021-04-26 20:20:59,031] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Partition erstesTopic-1 has an older epoch (0) than the current leader. Will await the new LeaderAndIsr state before resuming fetching. (kafka.server.ReplicaFetcherThread)
[2021-04-26 20:20:59,032] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Partition erstesTopic-1 marked as failed (kafka.server.ReplicaFetcherThread)
[2021-04-26 20:21:00,196] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions HashSet(erstesTopic-1, erstesTopic-0) (kafka.server.ReplicaFetcherManager)
[2021-04-26 20:21:00,198] INFO [ReplicaFetcherManager on broker 1] Added fetcher to broker 0 for partitions Map(erstesTopic-0 -> InitialFetchState(BrokerEndPoint(id=0, host=localhost:9092),2,4), erstesTopic-1 -> InitialFetchState(BrokerEndPoint(id=0, host=localhost:9092),1,4)) (kafka.server.ReplicaFetcherManager)
[2021-04-26 20:21:00,203] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions HashSet(__consumer_offsets-21, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-47, __consumer_offsets-31, __consumer_offsets-3, __consumer_offsets-37, __consumer_offsets-15, __consumer_offsets-17, __consumer_offsets-13, __consumer_offsets-43, __consumer_offsets-39, __consumer_offsets-29, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-19, __consumer_offsets-11, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5) (kafka.server.ReplicaFetcherManager)
[2021-04-26 20:21:24,126] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-04-26 20:21:24,128] INFO [KafkaServer id=1] shutting down (kafka.server.KafkaServer)
[2021-04-26 20:21:24,129] INFO [KafkaServer id=1] Starting controlled shutdown (kafka.server.KafkaServer)
[2021-04-26 20:21:24,622] INFO Unable to read additional data from server sessionid 0x1000009d4720008, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:24,726] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-04-26 20:21:24,726] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2021-04-26 20:21:26,237] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:28,285] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:28,394] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-04-26 20:21:29,714] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:31,756] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:33,373] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:35,415] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:36,661] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:38,713] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:40,093] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:42,148] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:43,641] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:45,692] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:47,968] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:49,988] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:51,559] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:53,602] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:55,263] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:57,278] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:21:58,601] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:22:00,633] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:22:02,514] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:22:03,629] INFO [GroupCoordinator 1]: Member[group.instance.id None, member.id consumer-console-consumer-45195-1-a2cddd8a-4ad3-4d84-895b-4632252c971e] in group console-consumer-45195 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-04-26 20:22:03,630] INFO [GroupCoordinator 1]: Preparing to rebalance group console-consumer-45195 in state PreparingRebalance with old generation 3 (__consumer_offsets-25) (reason: removing member consumer-console-consumer-45195-1-a2cddd8a-4ad3-4d84-895b-4632252c971e on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-04-26 20:22:03,630] INFO [GroupCoordinator 1]: Group console-consumer-45195 with generation 4 is now empty (__consumer_offsets-25) (kafka.coordinator.group.GroupCoordinator)
[2021-04-26 20:22:04,568] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:22:06,136] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:22:08,166] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-04-26 20:22:09,850] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
